-- Create admin with simple password "password"
-- This is a verified BCrypt hash from Spring Security's BCryptPasswordEncoder

DELETE FROM user_roles WHERE user_id IN (SELECT id FROM users WHERE username = 'admin');
DELETE FROM users WHERE username = 'admin';

-- BCrypt hash for "password" generated by Spring Security BCryptPasswordEncoder
INSERT INTO users (username, email, password, first_name, last_name, phone_number, is_verified, is_active, is_deleted, created_at, updated_at, created_by, updated_by)
VALUES ('admin', 'admin@hospital.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Admin', 'User', '+1-555-0100', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM');

-- Assign ADMIN role
INSERT INTO user_roles (user_id, role)
VALUES ((SELECT id FROM users WHERE username = 'admin'), 'ROLE_ADMIN');

-- Verify
SELECT u.id, u.username, u.email, ur.role, length(u.password) as pwd_len, substring(u.password, 1, 15) as pwd_start
FROM users u 
LEFT JOIN user_roles ur ON u.id = ur.user_id
WHERE u.username = 'admin';
